# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
#52d15db1cc01e0c3503367a43c3d6566bd3f66aa

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: Docker@2
  displayName: Login to Docker
  inputs:
    command: login
    containerRegistry: 'venkatesh07_Docker'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarrabo'
    organization: 'springbootvenkat'
    scannerMode: 'Other'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package -Dmaven.test.skip=true'
    sonarQubeRunAnalysis: true

#- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    repository: venkatesh07/test
    tags: latest
    containerRegistry: 'venkatesh07_Docker'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container' 