apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: rabobank-deployment 
spec: 
  selector: 
    matchLabels: 
      app: rabobank 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: rabobank 
    spec: 
      containers: 
      - name: rabobank 
        image: venkatesh07/test:latest
        imagePullPolicy: "Always"
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: rabobank-service 
spec: 
  selector: 
    app: rabobank 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 8080 
  type: LoadBalancer 
