apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabobank-deployment
  labels:
    app: rabobank
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabobank
  template:
    metadata:
      labels:
        app: rabobank
    spec:
      containers:
      - name: rabobank
        image: venkatesh07/test:latest
        ports:
        - containerPort: 8080
